name: Update Events

on:
  schedule:
    # Каждые 12 часов
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-events:
    runs-on: ubuntu-latest
    environment: events-update

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run events fetch script
      env:
        VK_TOKEN: ${{ secrets.VK_TOKEN }}
        YANDEX_KEY: ${{ secrets.YANDEX_KEY }}
        NOMINATIM_USER_AGENT: ${{ secrets.NOMINATIM_USER_AGENT }}
      run: python fetch_events.py

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/events.json public/geocode_cache.json
        git diff --staged --quiet || (git commit -m "Auto-update events from VK" && git push)
